### ISSUE TITLE
Изменить струру гема

### ISSUE THREAD

**Issue by zhabinka** [hexlet-components/ruby-pairs#3]
Изменить структуру в соответствие с соглашением – https://guides.rubygems.org/name-your-gem/
require 'hexlet/pairs'

**Comment by corsicanec82** [comment]
Обновил структуру. Для простоты решили наружу выставлять модуль Pairs без вложения в модуль Hexlet
https://hexlet.slack.com/archives/C035H4CUY/p1617728576222500
